version: '3.9'

services:

  web:
    image: nginx:1.24.0
    ports:
      - '8080:80'
    working_dir: /var/www/html
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
  
  composer:
    image: composer:latest
    command: sh -c "composer install --optimize-autoloader --no-dev --no-interaction"
    working_dir: /app
    volumes:
      - ./backend:/app 

  php-fpm:
    image: php:8.2.6-fpm
    command: php-fpm -c /usr/local/etc/php/php.ini-production
    working_dir: /var/www/html/backend
    volumes:
      - ./backend:/var/www/html/backend
